<?xml version="1.0" encoding="utf-8"?><Database Name="QLBH" Class="QuanLyBanHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=QLBH;Integrated Security=True" SettingsObjectName="FastFoodDemo.Properties.Settings" SettingsPropertyName="QLBHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HinhSP" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TT_Ban" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GiaSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIET_HD" Member="CHITIET_HDs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIET_HD" />
    </Type>
  </Table>
  <Table Name="dbo.PHANCONG" Member="PHANCONGs">
    <Type Name="PHANCONG">
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HeSo" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Association Name="NHANVIEN_PHANCONG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="CA_PHANCONG" Member="CA" ThisKey="MaCa" OtherKey="MaCa" Type="CA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TT_LamViec" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QuanLi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="PHANCONGs" ThisKey="MaNV" OtherKey="MaNV" Type="PHANCONG" />
      <Association Name="NHANVIEN_LUONG" Member="LUONGs" ThisKey="MaNV" OtherKey="MaNV" Type="LUONG" />
    </Type>
  </Table>
  <Table Name="dbo.LUONG" Member="LUONGs">
    <Type Name="LUONG">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayTL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Luong" Member="Luong1" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Association Name="NHANVIEN_LUONG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongGiaSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ngay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TT_HD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HOADON_CHITIET_HD" Member="CHITIET_HDs" ThisKey="MaHD" OtherKey="MaHD" Type="CHITIET_HD" />
    </Type>
  </Table>
  <Table Name="dbo.DOANHTHU_THANG" Member="DOANHTHU_THANGs">
    <Type Name="DOANHTHU_THANG">
      <Column Name="ThangBH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NamBH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DoanhThu_TH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongGiaSP_TH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongLuong_NV" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIET_HD" Member="CHITIET_HDs">
    <Type Name="CHITIET_HD">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIET_HD" Member="HOADON" ThisKey="MaHD" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIET_HD" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CA" Member="CAs">
    <Type Name="CA">
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LuongCa" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Association Name="CA_PHANCONG" Member="PHANCONGs" ThisKey="MaCa" OtherKey="MaCa" Type="PHANCONG" />
    </Type>
  </Table>
</Database>